### PR TITLE
Make GitHub ci

### PR DESCRIPTION
**Pull request by hiergaut**
* Make complete CI for linux, windows and macos.
Full pipeline when pull request on main branch :
configure -> build -> install -> test -> coverage -> cppcheck -> format -> doc
* Make full licensing of project and external
* Check history (remove confidential/large files)

### CODE REVIEW

**Comment by hiergaut** [comment]
After rebasing this branch to separate the different contributions made here and prevent future inter-contribution conflicts.
This branch is ready to be split in this unique order to avoid future conflicts :
cppCheck -> fix tests -> external licensing -> header versioning -> doxygen -> format (cmake,src) -> gitlab ci -> github ci
This branch do not be pushed, it will be deleted after complete splitting done

**Review by nmellado — CHANGES_REQUESTED** [review]
Post a changes request to prevent merging: the following PR is going to be split (as discussed AFK). 
In the meantime, it is kept open for change tracking.

**Comment by hiergaut** [comment]
@nmellado Can I close this splitted PR into (#7, #20, #17, #15, #21, #26, #27, #42) ?

**Comment by nmellado** [comment]
Sure, closing.

**Pull request closed without merging**
